### PR TITLE
Transferred sol on Solana

### PR DESCRIPTION
**Pull request by Finesse-734**
Issue: 6

#### Short description of what this resolves:
Signature: SLeTJaDAAmjrXS1CUs2h5x8tHr1kURZd5PVZFq2fn5i74f1247LQzh2zEEcwXjgKrTUFxnyg7PuaDVcPZ7PXiih
Slot: 182919392
Timestamp: December 18, 2022 15:31:09 India Standard Time
Nonce:4rTEKa9m4ACPmBmnreGW9gnMZXfaQN7XTtob1APeSvAz

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Srijan-crypto** [comment]
@Finesse-734  Nonce value is NOT correct .Please recheck

**Comment by Tan-Code-may** [comment]
@Finesse-734 I have updated this issue. Refer to it and make a fresh PR.

**Comment by Finesse-734** [comment]
> @Finesse-734 Nonce value is NOT correct .Please recheck

well how to get the nonce value as it is not visible on solscan.io from where I tranferred the testSol @Srijan-crypto 
here's is the transaction link: https://solscan.io/tx/SLeTJaDAAmjrXS1CUs2h5x8tHr1kURZd5PVZFq2fn5i74f1247LQzh2zEEcwXjgKrTUFxnyg7PuaDVcPZ7PXiih?cluster=devnet

**Comment by Tan-Code-may** [comment]
@Finesse-734 You need to search what nonce exactly means. It is not directly written there, but it is present.

**Pull request closed without merging**
