### PR TITLE
Create Vedant.txt

### PR DESCRIPTION
**Pull request by vedant-z**
Issue: 5

#### Short description of what this resolves:

Solana CLI

#### Changes proposed in this pull request and/or Screenshots of changes:

208401012-a0d61830-c39e-4c81-8939-fec14d3cd7da

### CODE REVIEW

**Comment by Srijan-crypto** [comment]
@vedant-z  Everything seems fine, just print your wallet address using a command in the screenshot. Also, hide the commands that you have used. It should be similar to the one attached in the issue.

**Comment by vedant-z** [comment]
@Srijan-crypto I have updated the PR

**Comment by Tan-Code-may** [comment]
@vedant-z Still you haven't printed your wallet address/Public key using a command.

**Comment by Tan-Code-may** [comment]
@vedant-z Do the required changes by today, else I'll close this PR.

**Pull request closed without merging**
