### PR TITLE
Update lib.rs

### PR DESCRIPTION
**Pull request by anshgeez31**
Issue: 28

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Srijan-crypto** [comment]
@anshgeez31 last 2 attributes of mint_to and first 2 attributes of create_account are not correct . Please make corrections.

**Comment by Srijan-crypto** [comment]
@anshgeez31 in `mint_to` you have put amount parameter as 10 . But we will be minting only one NFT. Change it with 1 . Everything else seems fine.

**Comment by anshgeez31** [comment]
@Srijan-crypto  Done

**Comment by Srijan-crypto** [comment]
Nice work.

**Pull request merged**
