### PR TITLE
Transferred SOL from wallet

### PR DESCRIPTION
**Pull request by Finesse-734**
Issue: 6

#### Short description of what this resolves:
have added the required text file

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Tan-Code-may** [comment]
@Finesse-734 Still your nonce value is incorrect. Also, do not change any other file, except, the one asked in the issue. You have changed three files. It will be easier to find nonce if you refer to Solana-explorer for viewing the transaction log.

**Comment by Finesse-734** [comment]
@Tan-Code-may have added the correct nonce value and removed the extra file.

**Comment by Tan-Code-may** [comment]
@Finesse-734 Well done! now everything is correct. Just delete both the .DS_Store and Task-6/.DS_Store files. They are not a part of my original repo, but they have been inserted in your PR.

**Comment by Finesse-734** [comment]
Well I have completed the required changes now @Tan-Code-may

**Pull request merged**
