### PR TITLE
Attached screenshot with pubKey

### PR DESCRIPTION
**Pull request by Finesse-734**
Issue: 5

#### Short description of what this resolves:
pubKey - kcE6673dztLWJkyah4ubqVEGxrLAuE8oLW1nzJ2RGUG
#### Changes proposed in this pull request and/or Screenshots of changes:
Screenshot 2022-12-18 at 15 43 46

-
-
-

### CODE REVIEW

**Comment by Tan-Code-may** [comment]
Hey, @Finesse-734 the screenshot does not match the one we uploaded in the issue. Please refer to it and update your PR.

**Comment by Finesse-734** [comment]
I am unable to get the attributes other than pubKey and balance from the terminal, so how should I move ahead on that?

**Comment by Finesse-734** [comment]
I have updated the screenshot as required.

**Comment by Tan-Code-may** [comment]
@Finesse-734 There was some error in the backend which is why the bot didn't assign you the points for this issue. But, now your points have been uploaded to the leaderboard manually. Keep contributing!

**Pull request merged**
